language: python
python:
  - '3.5'
sudo: false
env:
  - TOX_ENV=py35-flake8
  - TOX_ENV=py35-docs
  - TOX_ENV=py35-django1.9
matrix:
  fast_finish: true
install:
  - pip install tox
before_script:
  - createuser -U postgres jsonattrs
  - createdb -U postgres -O jsonattrs jsonattrs_test
script:
  - tox -e $TOX_ENV
notifications:
  slack:
    on_success: always
    on_failure: change
    secure: Nr9sFuXOhNvDagY7RvL0GfNmMzybLKy3inARg/xmCIkhhXUAuJ3pcSLNIEm9ONxIBwon9YRpzAADBWzfB07PcRX3Gf9t0mJLdu3tekaeW3hq9IZlvCpWpe6IGjhsn75WKyOi3K+tHPcKr4cHgjEDHLRtIzqvZ26EIxHZdbiEm1lZ+dCfAP0Uvsveq8EJ1byRD1lh2H9CX3SusxllGdfYR2cvjGBGxT/U7TspO6DKYezg0daNv/vztFWdDsgcVD8JFu2K9QwYyIQr2hwfEyKgxDW9cxdJi1cbLsVS1+aHaWbanK+F4xkqHSNmOBg7sCOT5AoVZvr4d52qJFWGWMLUTXWcNpJcigMy9DYw1NY9hzdgWjGFageg/G//W811/JlYDXP1cyRL0JAsC6Uim/MlnGrC0PE16gssN/IST3oEDqwTEmFci/QW1GJR4KqztVI5u+6zNMDFENdnBVRIMR9b8h/H6/ZIXU6caBH+nYla3EVAmwClcjlXxViEIjAKY/swOw1oBPE0uClTMbiRH9DpI+FJfwcGeege4USrgI6g6JFbqSWYNXCmHKtVnUAyejOvD9NCiFMtpkr9f9Ue+a4fLGynyaQADbdeiPrP7uod/O8THzEpPR0dXvFkC9tl4f0XTMV4jDvM+I4DRBYKMfQQzsSjurR1jqWt7+VPMM4NxqA=
