# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 11:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=50)),
                ('coarse_type', models.CharField(choices=[('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('CommaSeparatedIntegerField', 'CommaSeparatedIntegerField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FloatField', 'FloatField'), ('NullBooleanField', 'NullBooleanField'), ('SlugField', 'SlugField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('XMLField', 'XMLField'), ('BigIntegerField', 'BigIntegerField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SmallIntegerField', 'SmallIntegerField')], max_length=255)),
                ('subtype', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
                ('choices', models.CharField(blank=True, max_length=200)),
                ('default', models.CharField(blank=True, max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('omit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('schema', 'index'),
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256), default=list, null=True, size=None)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='jsonattrs.Schema'),
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together=set([('content_type', 'selectors')]),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('schema', 'name'), ('schema', 'index')]),
        ),
    ]
