# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(blank=True, max_length=50)),
                ('coarse_type', models.CharField(choices=[('AutoField', 'AutoField'), ('BooleanField', 'BooleanField'), ('CharField', 'CharField'), ('CommaSeparatedIntegerField', 'CommaSeparatedIntegerField'), ('DateField', 'DateField'), ('DateTimeField', 'DateTimeField'), ('DecimalField', 'DecimalField'), ('EmailField', 'EmailField'), ('FileField', 'FileField'), ('FloatField', 'FloatField'), ('ImageField', 'ImageField'), ('NullBooleanField', 'NullBooleanField'), ('SlugField', 'SlugField'), ('TimeField', 'TimeField'), ('URLField', 'URLField'), ('XMLField', 'XMLField'), ('BigIntegerField', 'BigIntegerField'), ('IntegerField', 'IntegerField'), ('PositiveIntegerField', 'PositiveIntegerField'), ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'), ('SmallIntegerField', 'SmallIntegerField')], max_length=255)),
                ('subtype', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField()),
                ('unique_together', models.BooleanField()),
                ('unique', models.BooleanField()),
                ('choices', models.CharField(blank=True, max_length=200)),
                ('default', models.CharField(blank=True, max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('omit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='jsonattrs.Schema')),
            ],
            options={
                'ordering': ('schema', 'index'),
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='jsonattrs.Schema'),
        ),
    ]
