# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonattrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='unique',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='unique_together',
        ),
    ]
