# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonattrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaselector',
            name='object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schemaselector',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='jsonattrs.Schema'),
        ),
    ]
