# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonattrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('schema', 'name'), ('schema', 'index')]),
        ),
    ]
