# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonattrs', '0002_auto_20160420_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaselector',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
