# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonattrs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrs', jsonattrs.fields.JSONAttributeField(null=True)),
            ],
            options={
                'ordering': ('department', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', jsonattrs.fields.JSONAttributeField(null=True)),
            ],
            options={
                'ordering': ('division', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', jsonattrs.fields.JSONAttributeField(null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', jsonattrs.fields.JSONAttributeField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='exampleapp.Department')),
            ],
            options={
                'ordering': ('department', 'name'),
            },
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='exampleapp.Division'),
        ),
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='exampleapp.Department'),
        ),
        migrations.AddField(
            model_name='contract',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Party'),
        ),
    ]
