# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import exampleapp.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', exampleapp.fields.EntityAttributeField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('attrs', exampleapp.fields.EntityAttributeField()),
            ],
            options={
                'ordering': ('project', 'address'),
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', exampleapp.fields.EntityAttributeField()),
            ],
            options={
                'ordering': ('project', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attrs', exampleapp.fields.EntityAttributeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Organization')),
            ],
            options={
                'ordering': ('organization', 'name'),
            },
        ),
        migrations.AddField(
            model_name='party',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Project'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.Project'),
        ),
    ]
