# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 15:19
from __future__ import unicode_literals

from django.db import migrations
import exampleapp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='attrs',
            field=exampleapp.fields.EntityAttributeField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='attrs',
            field=exampleapp.fields.EntityAttributeField(null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='attrs',
            field=exampleapp.fields.EntityAttributeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='attrs',
            field=exampleapp.fields.EntityAttributeField(null=True),
        ),
    ]
